import type { LLMProviderName } from './services/llmProviders';

export interface LLMConfig {
  provider: LLMProviderName;
  apiKey?: string;
  endpoint?: string;
  model?: string;
}

export type ThemeName = 'FANTASY' | 'CYBERPUNK' | 'SCI_FI' | 'HORROR' | 'NOIR' | 'STEAMPUNK' | 'SOLARPUNK' | 'POST_APOCALYPTIC' | 'WESTERN' | 'PIRATE';

export interface InventoryChanges {
  add?: string[];
  remove?: string[];
}

// New NPC types
export interface NPC {
  id: string; // A unique ID for the NPC, generated by the AI
  name: string;
  description: string; // Physical description, role, etc.
  status: string; // Current state, e.g., "friendly", "suspicious", "unconscious"
}

export interface NPCChanges {
  add?: NPC[];
  update?: (Partial<NPC> & { id: string })[]; // Can update multiple NPCs
  remove?: string[]; // Array of NPC IDs to remove
}

export interface Scene {
  title?: string;
  description: string;
  imagePrompt?: string;
  choices: string[];
  theme: ThemeName;
  inventory?: string[];
  worldState?: Record<string, string>;
  npcs?: NPC[];
}

export interface HistoryEntry {
  description: string;
  image: string;
}

export interface GameState {
  id: string; // Unique ID for the save file
  status: 'menu' | 'playing' | 'error';
  chat: any | null;
  history: HistoryEntry[];
  currentScene: Scene | null;
  currentImage: string | null;
  isLoading: boolean;
  error: string | null;
  currentTheme: ThemeName;
  inventory: string[];
  worldState: Record<string, string>;
  npcs: NPC[];
}

export interface Location {
    id: string;
    name: string;
    description: string;
}

export interface World {
    id: string;
    name: string;
    description: string;
    locations: Location[];
}

export interface SaveData {
    id: string;
    lastPlayed: string;
    theme: ThemeName;
    history: HistoryEntry[];
    chatHistory: any[];
    inventory: string[];
    worldState: Record<string, string>;
    npcs: NPC[];
    currentScene: Scene | null;
    currentImage: string | null;
    llmConfig: LLMConfig;
    world: World;
}

export interface ScenarioTemplate {
  id: string;
  title: string;
  prompt: string;
  image: string;
  category: 'Classic Adventures' | 'Weird & Wondrous Tales';
}
